<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <OutDir>$(MSBuildThisFileDirectory)..\..\artifacts\native\$(Configuration)\</OutDir>
    <IntDir>$(MSBuildThisFileDirectory)..\..\artifacts\native\obj\$(MSBuildProjectName)\</IntDir>
  </PropertyGroup>
  <ItemDefinitionGroup>
    <ClCompile>
      <WarningLevel>Level4</WarningLevel><TreatWarningAsError>true</TreatWarningAsError>
      <LanguageStandard>stdcpp17</LanguageStandard><RuntimeLibrary>MultiThreaded</RuntimeLibrary>
      <PreprocessorDefinitions>UNICODE;_UNICODE;WIN32_LEAN_AND_MEAN;NOMINMAX;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <AdditionalOptions>/utf-8 %(AdditionalOptions)</AdditionalOptions>
      <ExceptionHandling>Sync</ExceptionHandling><SDLCheck>true</SDLCheck>
    </ClCompile>
    <Link><AdditionalDependencies>ole32.lib;shell32.lib;shlwapi.lib;advapi32.lib;user32.lib;uuid.lib;%(AdditionalDependencies)</AdditionalDependencies></Link>
  </ItemDefinitionGroup>
</Project>
